### ISSUE TITLE
Rule comment-empty-line-before should be excluded

### ISSUE THREAD

**Issue by PythooonUser** [prettier/stylelint-config-prettier#133]
Hey :wave: 

The rule `comment-empty-line-before` should be excluded from the `stylelint` config as `prettier` can fix it automatically. It therefore does not need to be reported as a linting issue when using both tools.

Also, `stylelint` does not need to fix it, `prettier` can do so.

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKA7bAegCpsAVACwEsBnbB7AQ20gFsOEZsB3WjGrY4HAA4wAntgA2tKHGwAjOJgBOcVNjIki-WgBMhSbAEYADGIAeAbgIBfEABoQECbWj1koFmrUQ+AAVfBC8UFhk+FkkvFyU1FjAAazgYAGUWbgAZeThkdAj6ODiE5NS0sUT5AHNkGDUAV2KQURUDAzgDLJYoaoaWargAMQg1DhYYGBrkEBYGmAhnEGoYDhkAdTp4ekqwODTQwVoAN0FJGbB6WJB5IrUYQITq8fzC5oAreis0mpk4AEUGhB4K8ZEUXJU1HcLlclmI1PIYOtDEJkAAOcwQ-xFdYJMQzeFwO7HPIuACOQPgjzcYVm9AAtApOp0lhoKbQNI8Bi8kAUwc0ihxaHVGgLfgDKXleW8XDAWEpkUZqMgAEyyhK0OS9ADCEC4LBmRIArEsGkVKPKwnzwSBjk0AJJQDqwNJgBESACCTrSUj+oKK9nsQA)

**Comment by shannonmoeller** [comment]
Thanks for the issue. Prettier only ensures that there is never more than one empty line, but allows there to be zero or one empty lines. Since this rule can be configured to ensure or disallow empty lines it can still be configured to force a style the author prefers but prettier doesn't handle automatically. So, while there is some overlap, the rule doesn't conflict with prettier and shouldn't be turned off.

**Comment by PythooonUser** [comment]
Thanks, @shannonmoeller for that extended explanation. Very much appreciated!
