### ISSUE TITLE
Stylelint v15 "rule is deprecated"

### ISSUE THREAD

**Issue by shannonmoeller** [prettier/stylelint-config-prettier#140]
> **Note**  
> As of Stylelint v15 [all style-related rules have been deprecated](https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules). If you are using v15 or higher and are not making use of these deprecated rules, [this plugin is no longer necessary](https://stylelint.io/migration-guide/to-15#:~:text=Additionally%2C%20you%20may%20no%20longer%20need%20to%20extend%20Prettier%27s%20Stylelint%20config).

```diff
{
- "extends": ["stylelint-config-prettier"],
  "rules" { .. }
}
```

See also: #139

**Comment by thewilkybarkid** [comment]
I've just looked at removing this from a project, only to find a conflict between Stylelint and Prettier on https://github.com/PREreview/prereview.org/blob/0afee447961c9585202e5b63b2c837b48bbdb72b/assets/style.css#L12-L25 due to `at-rule-empty-line-before`, which is still enabled in `stylelint-config-standard`. (Prettier wants spaces between, Stylelint doesn't.)

Any idea if this is intentional or not?

**Comment by shannonmoeller** [comment]
The `at-rule-empty-line-before` rule has come up [quite a few times](https://github.com/prettier/stylelint-config-prettier/search?q=at-rule-empty-line-before&type=issues). At this point I think it would be better to discuss the conflict in the [stylelint-config-standard repo](https://github.com/stylelint/stylelint-config-standard).
